version: '3'
services:

  kali:
    container_name: kali
    hostname: kali
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 5900:5900
    tty: true
    #command: ./.start.sh; tail -F /dev/null
    restart: unless-stopped
